export const environment = {
  production: false,
  envName: 'local',

  //TEST
  keycloakConfig: {
    config: {
      url: 'http://192.168.88.82:8180/auth',
      // url: 'https://autosur.rawsur.com/auth',
      // url: 'https://auth.rawsur.com/auth',
        //  url: 'http://localhost:8180/auth',
      realm: 'rawsur',
      clientId: 'front-dgi',
    },
    initOptions: {
      onLoad: 'check-sso',
      // redirectUri: 'https://autosur.rawsur.com/home',
      // redirectUri: 'http://192.168.88.162:8095/home',
      // redirectUri: 'http://192.168.10.104:8095/home',
      redirectUri: 'http://localhost:8095/home',
      // redirectUri: 'http://192.168.88.95:8095/home',
      //  redirectUri: 'http://192.168.88.95:8095/home',
        //  redirectUri: 'http://localhost:8095/home',
    },
    loadUserProfileAtStartUp: true,
  },
  API_SNECA: {
    // URL_BASE :'https://autosur.rawsur.com/api-automobile/sneca/',
    // URL_BASE: 'https://sneca.rawsur.com/api/v1/sneca/response/auto/',
    URL_BASE: 'http://192.168.10.104:9005/api-automobile/sneca/',
    // URL_BASE: 'http://localhost:9005/api-automobile/sneca/',
    // URL_BASE: 'http://192.168.88.95:9005/api-automobile/sneca/',
    SUB_RESSOURCE: {
      RESPONSES: 'find/all',
      RESPONSE_BY_CERTIFICATE_REFERENCE: 'find/',
      RESPONSES_BY_CERTIFICATE_REFERENCES: 'find/all/byReferences',
      RESPONSESBYCODEASSURE: 'find/all/byPeriode/code',
      RESPONSES_BY_PERIODE_AND_INTERMEDIAIRES:
        'find/all/byPeriode/intermediaires',
      RESPONSES_BY_PERIODE_AND_PARTNERCODES: 'find/all/byPeriode/partnerCodes',
      RESPONSES_BY_PERIODE_AND_IMMATRICULATION_AND_INTERMEDIAIRES:
        'find/all/byPeriodeAndImmatriculationAndIntermediaires',
      RESPONSES_BY_PERIODE_AND_IMMATRICULATION_AND_PARTNERCODES:
        'find/all/byPeriodeAndImmatriculationAndPartnerCodes',
      RESPONSES_BY_PERIODE_AND_IMMATRICULATION_AND_CODEASSURE:
        'find/all/byPeriodeAndImmatriculationAndCodeAssure',
      RESPONSE_BY_IMMATRICULATION_AND_CODEASSURE:
        'find/all/byImmatriculationAndCodeAssure/',
      RESPONSES_BY_PERIODE: 'find/all/byPeriode',
      RESPONSES_BY_RISK_REFERENCE: 'find/all/byImmatriculation/',
      RESPONSEBYIMMATRICULATIONANDINTERMEDIAIRES:
        'find/all/byImmatriculation/intermediaires',
      RESPONSE_BY_IMMATRICULATIONAN_DPARTNERCODES:
        'find/all/byImmatriculation/codes',
      RESPONSES_BY_PERIODE_AND_RISK_REFERENCE:
        'find/all/byPeriodeAndImmatriculation',
      PRINT: 'print',
    },
  },
  API: {
    URL_BASE: 'http://192.168.10.104:9005/api/dgi/v1',

    // URL_BASE: 'http://192.168.88.95:9005/api/dgi/v1',
    // URL_BASE: 'http://192.168.88.82:9005/api-automobile/',
    // URL_BASE: 'http://192.168.88.95:9005/api/dgi/v1',
    SUB_RESSOURCE: {
      USER: '/user',
      ROLE: 'role/',
      CLIENT: 'client/',
      CATEGORY: 'category/',
      GUARANTEE: 'guarantee/',
      POLICY: 'policy/',
      SUBSCRIPTION: 'subscription/',
      POLICYVOYAGE: 'policyVoyage/',
      RISK: 'risk/',
      HISTORY: 'history/',
      CERTIFICAT: 'certificate/',
      PARAMETERS: 'parameter/',
      INTERMEDIAIRE: '/intermediary',
      BRANCH: 'branch/',
      PERMISSION: 'permission/',
      CODEASSUREPARTENAIRE: 'codeAssurePartenanire/',
      ACTION: 'action/',
      UNIT: 'unit/',
      SNECA: 'v1/sneca/',
      PROVINCE: 'province/',
      VILLE: 'ville/',
      CODIFICATION: 'codification/',
      SHOP: '/shop',
      INVOICE: '/rawsur-invoice',
      EXCHANGE_RATE: '/exchange-rate',
      ENTREPRISE: '/entreprise',
    },
    V1: {
      ADD: 'v1/create',
      //createmany
      GET_DGI_INVOICE: '/get-dgi-invoice',
      CREATE_DGI_INVOICE: '/create-dgi-invoice',
      PRINT_DGI_INVOICE: '/print-dgi-invoice',
      ADD_MANY_PERMISSIONS: 'v1/createmany',
      ADDUSERCODEPARTENAIRE: 'v1/createmany',
      ADDPARTNERCODEPARTENAIRE: 'v1/createCode',
      REQUEST_ARCA: 'v1/request-arca',
      REQUEST_ARCA_CANCEL: 'v1/request-arca-cancel',
      RESPONSE_ARCA: 'v1/response-arca/',
      RESPONSE_SNECA_ALL: 'response/find/all/',
      RESPONSE_SNECA_BY_ENVID: 'response/find/envid/',
      GET_BY_NUMERO_CERTIFICAT: 'v1/get-by-numerocertificat',
      AFFECTED_USER: 'v1/affected',
      CREATE_USER_INTERMEDIAIRIES: '/create-user-intermediairies',
      CREATE_USER_SHOP: '/create-user-shop',
      UPDATE: 'v1/update',
      EDIT: '/edit',
      REPPORT: 'v1/report',
      DELETE: 'v1/delete/',
      GET_ALL: '/list',
      GET_ALL_CODES_FROM_PARTNER: 'v1/list/',
      GET_ALL_CODES_BY_TOKEN: 'v1/list/fromToken',
      GET_ALL_FROM_INTERMEDIAIRES: 'v1/list/intermediaires',
      GET_ALL_FROM_PARTNER_CODES: 'v1/list/codes',
      GET_SUBSCRIPTIONS_BY_PERIOD: 'v1/subscriptions-by-period',
      CANCEL_POLICY: 'v1/travel/cancel/',
      GET_ALL_FROM_INTERMEDIAIRES_AND_NUMPOLICY:
        'v1/list/intermediaires/numPolicy', //byCodeAssure/byNumPolicy
      GET_ALL_FROM_INTERMEDIAIRES_AND_NUMPOLICY_GOSUR:
        'v1/policies/list/intermediaires/numPolicy',
      GET_ALL_GOSUR_BY_PERIOD: 'v1/policies-period',
      GET_ALL_AXA_BY_PERIOD: 'v1/travel/policiesbydate',
      GET_AXA_POLICY_BY_ID: 'v1/travel/policies/',
      GOSUR_SUSCRIBE: 'v1/suscribe',
      GOSUR_SUSCRIPTION_DATA: 'v1/policyData/',
      GET_ALL_FROM_PARTNER_CODES_AND_NUMPOLICY: 'v1/list/codes/numPolicy', //b
      GET_ALL_FROM_CODE_ASSURE_AND_NUMPOLICY:
        'v1/list/byCodeAssure/byNumPolicy',
      GET_ALL_BY_USER: 'v1/list/byUser',
      GET_ALL_FOR_ADMIN_USER: 'v1/list-all',
      GET_ALL_BY_STATUS: 'v1/list-by-status/',
      GET_ALL_BY_DATE: 'v1/list-by-date/',
      GET_ALL_SECONDARY: 'v1/list-secondary',
      GET_ALL_BY_CLIENT: 'v1/list-by-client/',
      GET_ALL_BY_CLIENT_AND_PERIODE: 'v1/list-by-client-and-periode/',
      GET_WITH_GARANTIES: 'v1/list-with-guaranties',
      GET: 'v1/get/',
      GET_USER_FROM_TOKEN: '/me',
      CHANGE_STATUS: 'v1/change-status',
      AUTH: 'v1/authentication',
      AUTH_BY_EMAIL: 'v1/get-user-by-email/',
      CHANGE_STATUS_READ: 'v1/change-status-read',
      MAP_USER_INTERM_PERMISSSION: 'v1/map-user-interm-permission',
      RENEWAL: 'v1/renewal',
      SOUSCRIPTION: 'request/transport/send/souscription/',
      POLICIES_NUM_POLICY: 'v1/list/byNumPolicy',
      POLICY_NUM_POLICY_CODE_INT_NUM_AVE:
        'v1/getOneByNumPolicyAndCodeIntAndCodeNumeAve/',
      POLICIES_CODE_ASSURE: 'v1/list/byCodeAssure',
      RISKS_NUM_POLICY: 'v1/list/risksByPolicy',
      RISK_BY_IMMATRICULATION: 'v1/',
      HISTORY_CREATE: 'v1/create',
      HISTORIES_LIST: 'v1/list',
      HISTORIES_LIST_BY_PERIOD: 'find/all/byPeriode',
      GET_RAPPORT: 'find/rapport',
      HISTORIES_LIST_BY_OBJECT_NAME: 'find/all/byObjectName',
      HISTORIES_LIST_BY_PERIOD_AND_OBJECT_NAME:
        'find/all/byPeriodeAndObjectName',
      GET_CODIFICATIONS_BY_NOM_CODIFICATION: 'v1/find-by-nom-codification/',
    },
  },

  // PROD

  // keycloakConfig: {
  //   config: {
  //     // url: 'https://autosur.rawsur.com/auth',
  //     url: 'http://192.168.88.82:8180/auth',
  //     // url: 'http://192.168.88.162:8080',
  //     realm: 'rawsur',
  //     clientId: 'auto-frontend',
  //   },
  //   initOptions: {
  //     onLoad: 'check-sso',
  //     redirectUri: "http://192.168.88.162:8095/home",
  //     // redirectUri: 'https://autosur.rawsur.com/home',
  //   },
  //   loadUserProfileAtStartUp: true,
  // },
  // API_SNECA: {
  //   // URL_BASE: 'https://autosur.rawsur.com/api/v1/sneca/response/auto/',
  //   URL_BASE: 'http://192.168.88.162:9005/api-automobile/sneca/',
  //   // URL_BASE: 'https://sneca.rawsur.com/api/v1/sneca/response/auto/',
  //   SUB_RESSOURCE: {
  //     RESPONSES: 'find/all',
  //     RESPONSE_BY_CERTIFICATE_REFERENCE: 'find/',
  //     RESPONSES_BY_CERTIFICATE_REFERENCES: 'find/all/byReferences',
  //     RESPONSESBYCODEASSURE: 'find/all/byPeriode/code',
  //     RESPONSES_BY_PERIODE_AND_INTERMEDIAIRES:
  //       'find/all/byPeriode/intermediaires',
  //     RESPONSES_BY_PERIODE_AND_PARTNERCODES: 'find/all/byPeriode/partnerCodes',
  //     RESPONSES_BY_PERIODE_AND_IMMATRICULATION_AND_INTERMEDIAIRES:
  //       'find/all/byPeriodeAndImmatriculationAndIntermediaires',
  //     RESPONSES_BY_PERIODE_AND_IMMATRICULATION_AND_PARTNERCODES:
  //       'find/all/byPeriodeAndImmatriculationAndPartnerCodes',
  //     RESPONSES_BY_PERIODE_AND_IMMATRICULATION_AND_CODEASSURE:
  //       'find/all/byPeriodeAndImmatriculationAndCodeAssure',
  //     RESPONSE_BY_IMMATRICULATION_AND_CODEASSURE:
  //       'find/all/byImmatriculationAndCodeAssure/',
  //     RESPONSES_BY_PERIODE: 'find/all/byPeriode',
  //     RESPONSES_BY_RISK_REFERENCE: 'find/all/byImmatriculation/',
  //     RESPONSEBYIMMATRICULATIONANDINTERMEDIAIRES:
  //       'find/all/byImmatriculation/intermediaires',
  //     RESPONSE_BY_IMMATRICULATIONAN_DPARTNERCODES:
  //       'find/all/byImmatriculation/codes',
  //     RESPONSES_BY_PERIODE_AND_RISK_REFERENCE:
  //       'find/all/byPeriodeAndImmatriculation',
  //   },
  // },
  // API: {
  //   URL_BASE: 'http://192.168.88.162:9005/api-automobile/',
  //   // URL_BASE: 'http://192.168.88.82:80/api-automobile/',
  //   SUB_RESSOURCE: {
  //     USER: 'user/',
  //     ROLE: 'role/',
  //     CLIENT: 'client/',
  //     CATEGORY: 'category/',
  //     GUARANTEE: 'guarantee/',
  //     POLICY: 'policy/',
  //     RISK: 'risk/',
  //     HISTORY: 'history/',
  //     CERTIFICAT: 'certificate/',
  //     PARAMETERS: 'parameter/',
  //     INTERMEDIAIRE: 'intermediary/',
  //     BRANCH: 'branch/',
  //     PERMISSION: 'permission/',
  //     CODEASSUREPARTENAIRE: 'codeAssurePartenanire/',
  //     ACTION: 'action/',
  //     UNIT: 'unit/',
  //     SNECA: 'v1/sneca/',
  //   },
  //   V1: {
  //     ADD: 'v1/create',
  //     //createmany
  //     ADD_MANY_PERMISSIONS: 'v1/createmany',
  //     ADDUSERCODEPARTENAIRE: 'v1/createmany',
  //     ADDPARTNERCODEPARTENAIRE: 'v1/createCode',
  //     REQUEST_ARCA: 'v1/request-arca',
  //     REQUEST_ARCA_CANCEL: 'v1/request-arca-cancel',
  //     RESPONSE_ARCA: 'v1/response-arca/',
  //     RESPONSE_SNECA_ALL: 'response/find/all/',
  //     RESPONSE_SNECA_BY_ENVID: 'response/find/envid/',
  //     GET_BY_NUMERO_CERTIFICAT: 'v1/get-by-numerocertificat',
  //     AFFECTED_USER: 'v1/affected',
  //     UPDATE: 'v1/update',
  //     REPPORT: 'v1/report',
  //     DELETE: 'v1/delete/',
  //     GET_ALL: 'v1/list',
  //     GET_ALL_CODES_FROM_PARTNER: 'v1/list/',
  //     GET_ALL_CODES_BY_TOKEN: 'v1/list/fromToken',
  //     GET_ALL_FROM_INTERMEDIAIRES: 'v1/list/intermediaires',
  //     GET_ALL_FROM_PARTNER_CODES: 'v1/list/codes',
  //     GET_ALL_FROM_INTERMEDIAIRES_AND_NUMPOLICY:
  //       'v1/list/intermediaires/numPolicy', //byCodeAssure/byNumPolicy
  //     GET_ALL_FROM_PARTNER_CODES_AND_NUMPOLICY: 'v1/list/codes/numPolicy', //b
  //     GET_ALL_FROM_CODE_ASSURE_AND_NUMPOLICY:
  //       'v1/list/byCodeAssure/byNumPolicy',
  //     GET_ALL_BY_USER: 'v1/list/byUser',
  //     GET_ALL_FOR_ADMIN_USER: 'v1/list-all',
  //     GET_ALL_BY_STATUS: 'v1/list-by-status/',
  //     GET_ALL_BY_DATE: 'v1/list-by-date/',
  //     GET_ALL_SECONDARY: 'v1/list-secondary',
  //     GET_ALL_BY_CLIENT: 'v1/list-by-client/',
  //     GET_ALL_BY_CLIENT_AND_PERIODE: 'v1/list-by-client-and-periode/',
  //     GET_WITH_GARANTIES: 'v1/list-with-guaranties',
  //     GET: 'v1/get/',
  //     GET_USER_FROM_TOKEN: 'v1/user/keycloackId',
  //     CANCEL: 'v1/cancel/',
  //     CHANGE_STATUS: 'v1/change-status',
  //     AUTH: 'v1/authentication',
  //     AUTH_BY_EMAIL: 'v1/get-user-by-email/',
  //     CHANGE_STATUS_READ: 'v1/change-status-read',
  //     MAP_USER_INTERM_PERMISSSION: 'v1/map-user-interm-permission',
  //     RENEWAL: 'v1/renewal',
  //     SOUSCRIPTION: 'request/transport/send/souscription/',
  //     POLICIES_NUM_POLICY: 'v1/list/byNumPolicy',
  //     POLICY_NUM_POLICY_CODE_INT_NUM_AVE:
  //       'v1/getOneByNumPolicyAndCodeIntAndCodeNumeAve/',
  //     POLICIES_CODE_ASSURE: 'v1/list/byCodeAssure',
  //     RISKS_NUM_POLICY: 'v1/list/risksByPolicy',
  //     RISK_BY_IMMATRICULATION: 'v1/',
  //     HISTORY_CREATE: 'v1/create',
  //     HISTORIES_LIST: 'v1/list',
  //     HISTORIES_LIST_BY_PERIOD: 'find/all/byPeriode',
  //     HISTORIES_LIST_BY_OBJECT_NAME: 'find/all/byObjectName',
  //     HISTORIES_LIST_BY_PERIOD_AND_OBJECT_NAME:
  //       'find/all/byPeriodeAndObjectName',
  //   },
  // },
};
