import { Attestation } from './attestation';
import { RequestApag } from './Request';
import { UserItem } from './UserItem';

export interface Demande {
  id: string;
  date_demande_edition: string;
  date_souscription: string;
  date_effet: string;
  date_echeance: string;
  genre_vehicule: string;
  numero_immatriculation: string;
  type_vehicule: string;
  model_vehicule: string;
  categorie_vehicule: string;
  usage_vehicule: string;
  source_energie: string;
  nombre_place: string;
  marque_vehicule: string;
  numero_chassis: string;
  numero_moteur: string;
  numero_carte_brune_physique: string;
  numero_rccm: string;
  bureau_enregistreur: string;
  nom_souscripteur: string;
  type_souscripteur: string;
  adresse_mail_souscripteur: string;
  numero_telephone_souscripteur: string;
  boite_postale_souscripteur: string;
  type_assure: string;
  nom_assure: string;
  adresse_mail_assure: string;
  boite_postale_assure: string;
  numero_police: string;
  numero_telephone_assure: string;
  profession_assure: string;
  type_point_vente_compagnie: string;
  code_point_vente_compagnie: string;
  denomination_point_vente_compagnie: string;
  rc: string;
  code_nature_attestation: string;
  garantie: string;
  contrat: string;
  zone_circulation: string;
  date_premiere_mise_en_circulation: string;
  valeur_neuve: string;
  valeur_venale: string;
  montant_autres_garanties: string;
  montant_prime_nette_total: string;
  montant_accessoires: string;
  montant_taxes: string;
  montant_carte_brune: string;
  fga: string;
  montant_prime_ttc: string;
  reference_attestation: string;
  attestations: Attestation[];
  request: RequestApag;
  createdAt: Date;
  userHasCreated: UserItem;
}
