export interface Policy{
  accessoires: number;
  adresse: string;
  assure: string;
  civilite: string;
  cle: string;
  code_assure: number;
  codeint: string;
  duree: number;
  effectDate: Date;
  emissionDate: Date;
  immatriculation: string;
  issueDate: Date;
  lieunais: string;
  nomAssure: string;
  numearca: string;
  numeave: number;
  numpoli: string;
  pays_etablissement: string;
  pers_morale: string;
  phone: string;
  prime_nette: number;
  profession: string;
  reference: string;
  sexeassu: string;
  taxe: number;
  total: number;
  type_avenant: string;
}
