import { Demande } from "./Demande";

export interface Risk {
  id: number;
  cle: string;
  codeint: number;
  numpoli: number;
  numave: number;
  dateDemandeEdition: Date | string;
  dateSouscription: Date | string;
  dateEffet: Date | string;
  dateEcheance: Date | string;
  genreVehicule: string;
  numeroImmatriculation: string;
  typeVehicule: string;
  modelVehicule: string;
  categorieVehicule: number;
  usageVehicule: string;
  sourceEnergie: string;
  nombrePlace: number;
  marqueVehicule: string;
  numeroChassis: string;
  numeroMoteur: string;
  numeroCarteBrunePhysique: string;
  numeroRccm: string;
  bureauEnregistreur: string;
  nomSouscripteur: string;
  typeSouscripteur: string;
  adresseMailSouscripteur: string;
  numeroTelephoneSouscripteur: string;
  boitePostaleSouscripteur: string;
  typeAssure: string;
  nomAssure: string;
  adresseMailAssure: string;
  boitePostaleAssure: string;
  numeroPolice: string;
  numeroTelephoneAssure: string;
  professionAssure: number;
  typePointVenteCompagnie: string;
  codePointVenteCompagnie: number;
  denominationPointVente: string;
  rc: number;
  codeNatureAttestation: string;
  garantie: string;
  contrat: string;
  zoneCirculation: string;
  datePremiereMec: Date | string;
  valeurNeuve: number;
  valeurVenale: number;
  montantAutresGaranties: number;
  montantPrimeNetteTotal: number;
  montantAccessoires: number;
  montantTaxes: number;
  montantCarteBrune: number;
  fga: number;
  montantPrimeTtc: number;
  demande:Demande;
  hasCertificate: boolean;
  certificateReference: string;
  isWaiting: boolean;
  certificate: string;
  pdfSaved: boolean;
  numeroCertificatToPrint: string;
  isChecked: boolean;
  isCheckedForPrint: boolean;
  status: boolean;
  vResponse: any;
  waiting: boolean;
}
